name: Ronex Design
favicon: null
layout_spectrum: 0.3958608480170369
typography_spectrum: 0.7390146590769291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffae4'
    - '#323232'
    - '#95c7ce'
    - '#837864'
    - '#ff5b3b'
  brandStrength: 0.8125
  lightness: 0.9436326844152063
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
