name: Ronex Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25153
title: Gamification Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffae4'
    - '#323232'
    - '#95c7ce'
    - '#837864'
    - '#ff5b3b'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
